# Site settings
title: The Emerald LUX
description: "Lux project for self-learning, build with Emerald-Jekyll."
url: "https://luxowner.github.io"
author:
  name: "Lucifer Samael Morningstar"
  email: "lucathar@proton.me"
  url: "https://luxowner.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "6.6.6"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
